# Generated by Django 3.2.9 on 2021-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('LR', 'Living Room'), ('KC', 'Kitchen'), ('R', 'Room')], default='LR', max_length=200)),
                ('room_image', models.ManyToManyField(to='dashboard.Image')),
            ],
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
