# Generated by Django 3.2.9 on 2021-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211208_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='funiture_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
