# Generated by Django 3.2.9 on 2021-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='funiture_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
