# Generated by Django 3.2.9 on 2021-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_funiture_object_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='funiture',
            name='object_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
