# Generated by Django 3.2.9 on 2021-12-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_funiture_object_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
