# Generated by Django 3.2.9 on 2021-12-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='theme',
            field=models.CharField(choices=[('French', 'French'), ('Japanese', 'Japanese')], default='Japanese', max_length=200),
        ),
    ]
